name: MSUM ACM
description: The blog of MSUM's ACM chapter
pygments: true
url :   http://msumacm.org
permalink: /:month-:day-:year/:title
markdown: rdiscount
timezone: America/Chicago
rdiscount:
    extensions: [smart]
